### PR TITLE
fix(tests): read at most 1024 lines of logs before rpc server output

### LINKED ISSUE #555: staking-miner integration tests failed against latest polkadot build.
Go to https://gitlab.parity.io/parity/mirrors/staking-miner-v2/-/pipelines/271250 to see details about the failure.

### PR DESCRIPTION
**Pull request by niklasad1**
Close #555

### CODE REVIEW

File: tests/common.rs [hunk 1]
```diff
@@ -22,7 +22,7 @@ pub fn find_ws_url_from_output(read: impl Read + Send) -> (String, String) {
 
 	let ws_url = BufReader::new(read)
 		.lines()
-		.take(50)
+		.take(1024)
```
Comment (niklasad1) [inline tests/common.rs:25]:
```suggestion
		.take(1024 * 1024)
```
